using Test

import CloudMicrophysics.Parameters as CMP
import CloudMicrophysics.BulkMicrophysicsTendencies as BMT
import CloudMicrophysics.ThermodynamicsInterface as TDI

# A1: the AD-vs-manual 2M+P3 Jacobian corpus battery.
#
# Compares `ManualJacobian` (`_jacobian_2mp3_manual`, `_jacobian_2mp3t_manual`) against
# `ExactJacobian` (`ForwardDiff`) at a fixed corpus of physically realized states, for
# both the eight-species substep state and the temperature-coupled nine-vector.
#
# WHAT THIS FILE VERIFIES WITH A NUMERIC TOLERANCE, and where the tolerance comes from:
#   - The condensation self-derivative (the `(q_lcl, q_lcl)` entry) agrees with the AD
#     reference to a ratio of 1.0 at four significant figures, at every corpus state.
#     This is the one entry `docs/src/RosenbrockNumerics.md` ("Numerical verification")
#     measures directly, and the number this file locks (`rtol = 1e-4`) is that
#     document's own figure.
#   - The temperature-coupled state's structural identities (`Ṫ = cᵀf`, the temperature
#     row `cᵀf_q`, the temperature corner `cᵀf_T`, and the species block matching
#     `ManualJacobian`'s own output) are the same page's "by construction" claims; the
#     tolerances here are the same order as the ones quoted there (`1e-14`, `~1e-9`,
#     `~1e-11`, exact at `Float64`) but loosened by one to three orders as a margin
#     against implementation details this file did not itself measure.
#
# WHAT THIS FILE DOES NOT VERIFY NUMERICALLY: every other Jacobian entry is a mix of
# closed-form (Tier 1) and donor-linearized (Tier 2/3) contributions accumulated into
# the same matrix cell (see the tier commentary on `_jacobian_2mp3_manual`), so no
# single tolerance describes it and none is documented. Those entries are asserted
# finite at both precisions only - which is the corpus's other job, exercising the
# `logλ = -Inf` and near-zero-population rows without producing non-finite output - not
# checked against the AD reference. Locking real per-entry tolerances for them needs a
# run on a compute node against this corpus, which this environment does not have.
#
# The 31 entries `_jacobian_2mp3_manual` never assembles (the corresponding keyword of
# `_jacobian_2mp3` is not passed at its call site, so the entry is exactly that
# keyword's `zero(FT)` default at every state, provable from the source rather than
# measured) are asserted exactly zero on the manual side and excluded from the AD
# comparison entirely: they are documented Tier-2/3 omissions (donor-linearized
# couplings the manual matrix does not carry), not places where the true derivative is
# zero, so comparing them against a nonzero AD entry would be asserting the wrong thing.

#####
##### Corpus: the 20 warm-liquid rows of the campaign's tcoupling extract
#####
# Source: /glade/derecho/scratch/haakone/runs/p3-2mp3-stability/20260810-tcoupling-slice1/states.csv
# (378 rows: 344 `battery`, 14 `checkpoint`, 20 `warmliq`; these are the 20 `warmliq` rows,
# the corpus `docs/src/RosenbrockNumerics.md`'s "Numerical verification" section cites).
# Generated by `p3-2mp3-stability/diag/tcoupling_extract_states.jl` from a coupled
# single-column run; `source_detail` below is that generator's own cell identifier,
# kept as the provenance trail back to the run. Embedded as literals, rather than read
# from the scratch file, so this battery survives outside this machine. Column order:
# (ρ, T, q_tot, q_lcl, n_lcl, q_rai, n_rai, q_ice, n_ice, q_rim, b_rim, logλ, w, p).
# Several rows repeat bit-for-bit: they are distinct grid cells that landed on the same
# state at this extraction time, not a corpus-construction artifact, and are kept as
# extracted so the corpus matches the twenty rows the docs page counts.
const CORPUS = [
    # source_detail = leg1_day4.0.hdf5_e3i4j4lev9
    (
        ρ = 1.0768013000488281, T = 291.8062871141631, q_tot = 0.015939239689095285,
        q_lcl = 0.0008379385390150068, n_lcl = 9.263111401841454e7,
        q_rai = 0.0001496757002143091, n_rai = 16812.515252748188,
        q_ice = 0.0, n_ice = 0.0, q_rim = 0.0, b_rim = 0.0,
        logλ = -Inf, w = 0.0, p = 0.0,
    ),
    # source_detail = leg1_day4.0.hdf5_e8i1j4lev9 (bit-identical to the row above)
    (
        ρ = 1.0768013000488281, T = 291.8062871141631, q_tot = 0.015939239689095285,
        q_lcl = 0.0008379385390150068, n_lcl = 9.263111401841454e7,
        q_rai = 0.0001496757002143091, n_rai = 16812.515252748188,
        q_ice = 0.0, n_ice = 0.0, q_rim = 0.0, b_rim = 0.0,
        logλ = -Inf, w = 0.0, p = 0.0,
    ),
    # source_detail = leg1_day4.0.hdf5_e9i1j1lev9 (bit-identical to the row above)
    (
        ρ = 1.0768013000488281, T = 291.8062871141631, q_tot = 0.015939239689095285,
        q_lcl = 0.0008379385390150068, n_lcl = 9.263111401841454e7,
        q_rai = 0.0001496757002143091, n_rai = 16812.515252748188,
        q_ice = 0.0, n_ice = 0.0, q_rim = 0.0, b_rim = 0.0,
        logλ = -Inf, w = 0.0, p = 0.0,
    ),
    # source_detail = leg1_day4.0.hdf5_e14i4j1lev9 (bit-identical to the row above)
    (
        ρ = 1.0768013000488281, T = 291.8062871141631, q_tot = 0.015939239689095285,
        q_lcl = 0.0008379385390150068, n_lcl = 9.263111401841454e7,
        q_rai = 0.0001496757002143091, n_rai = 16812.515252748188,
        q_ice = 0.0, n_ice = 0.0, q_rim = 0.0, b_rim = 0.0,
        logλ = -Inf, w = 0.0, p = 0.0,
    ),
    # source_detail = leg1_day4.0.hdf5_e3i4j4lev11
    (
        ρ = 1.0190671682357788, T = 289.6490281258372, q_tot = 0.01514805901406729,
        q_lcl = 0.0012225938925131206, n_lcl = 1.0209106057269141e8,
        q_rai = 6.825993442294488e-5, n_rai = 45015.91230798655,
        q_ice = 0.0, n_ice = 0.0, q_rim = 0.0, b_rim = 0.0,
        logλ = -Inf, w = 0.0, p = 0.0,
    ),
    # source_detail = leg5_day20.0.hdf5_e51i1j4lev11
    (
        ρ = 1.0307297706604004, T = 286.23506704487613, q_tot = 0.011461100866627775,
        q_lcl = 9.89584316139258e-5, n_lcl = 9.53061750967567e7,
        q_rai = 6.51625458280238e-5, n_rai = 280.19399360750407,
        q_ice = 2.3473643198486555e-6, n_ice = 0.3223877993909133,
        q_rim = 2.3322348223080127e-6, b_rim = 2.639051977013808e-9,
        logλ = 6.583126752512999, w = 0.0, p = 0.0,
    ),
    # source_detail = leg5_day20.0.hdf5_e52i1j1lev11 (bit-identical to the row above)
    (
        ρ = 1.0307297706604004, T = 286.23506704487613, q_tot = 0.011461100866627775,
        q_lcl = 9.89584316139258e-5, n_lcl = 9.53061750967567e7,
        q_rai = 6.51625458280238e-5, n_rai = 280.19399360750407,
        q_ice = 2.3473643198486555e-6, n_ice = 0.3223877993909133,
        q_rim = 2.3322348223080127e-6, b_rim = 2.639051977013808e-9,
        logλ = 6.583126752512999, w = 0.0, p = 0.0,
    ),
    # source_detail = leg5_day20.0.hdf5_e53i4j1lev11 (bit-identical to the row above)
    (
        ρ = 1.0307297706604004, T = 286.23506704487613, q_tot = 0.011461100866627775,
        q_lcl = 9.89584316139258e-5, n_lcl = 9.53061750967567e7,
        q_rai = 6.51625458280238e-5, n_rai = 280.19399360750407,
        q_ice = 2.3473643198486555e-6, n_ice = 0.3223877993909133,
        q_rim = 2.3322348223080127e-6, b_rim = 2.639051977013808e-9,
        logλ = 6.583126752512999, w = 0.0, p = 0.0,
    ),
    # source_detail = leg5_day20.0.hdf5_e56i4j4lev11 (bit-identical to the row above)
    (
        ρ = 1.0307297706604004, T = 286.23506704487613, q_tot = 0.011461100866627775,
        q_lcl = 9.89584316139258e-5, n_lcl = 9.53061750967567e7,
        q_rai = 6.51625458280238e-5, n_rai = 280.19399360750407,
        q_ice = 2.3473643198486555e-6, n_ice = 0.3223877993909133,
        q_rim = 2.3322348223080127e-6, b_rim = 2.639051977013808e-9,
        logλ = 6.583126752512999, w = 0.0, p = 0.0,
    ),
    # source_detail = leg5_day20.0.hdf5_e57i4j3lev11
    (
        ρ = 1.032044768333435, T = 285.88587581547705, q_tot = 0.011055469086687383,
        q_lcl = 6.517135167446412e-5, n_lcl = 9.669028617929108e7,
        q_rai = 5.9041408266920765e-5, n_rai = 114.85706028551928,
        q_ice = 2.8742589049146624e-7, n_ice = 0.050995950698470294,
        q_rim = 2.833813978103805e-7, b_rim = 3.18406972454056e-10,
        logλ = 6.614699702682897, w = 0.0, p = 0.0,
    ),
    # source_detail = leg10_day40.0.hdf5_e5i4j4lev12
    (
        ρ = 0.9960068464279175, T = 283.9228271321616, q_tot = 0.011092031721661148,
        q_lcl = 0.000632087021532389, n_lcl = 9.96530178040129e7,
        q_rai = 0.0004696894067483065, n_rai = 3604.341664401586,
        q_ice = 5.086218276923644e-8, n_ice = 0.055778889412719954,
        q_rim = 4.9061079891157945e-8, b_rim = 5.384917375632014e-11,
        logλ = 7.1727433959224545, w = 0.0, p = 0.0,
    ),
    # source_detail = leg10_day40.0.hdf5_e6i1j4lev12 (bit-identical to the row above)
    (
        ρ = 0.9960068464279175, T = 283.9228271321616, q_tot = 0.011092031721661148,
        q_lcl = 0.000632087021532389, n_lcl = 9.96530178040129e7,
        q_rai = 0.0004696894067483065, n_rai = 3604.341664401586,
        q_ice = 5.086218276923644e-8, n_ice = 0.055778889412719954,
        q_rim = 4.9061079891157945e-8, b_rim = 5.384917375632014e-11,
        logλ = 7.1727433959224545, w = 0.0, p = 0.0,
    ),
    # source_detail = leg10_day40.0.hdf5_e7i1j1lev12 (bit-identical to the row above)
    (
        ρ = 0.9960068464279175, T = 283.9228271321616, q_tot = 0.011092031721661148,
        q_lcl = 0.000632087021532389, n_lcl = 9.96530178040129e7,
        q_rai = 0.0004696894067483065, n_rai = 3604.341664401586,
        q_ice = 5.086218276923644e-8, n_ice = 0.055778889412719954,
        q_rim = 4.9061079891157945e-8, b_rim = 5.384917375632014e-11,
        logλ = 7.1727433959224545, w = 0.0, p = 0.0,
    ),
    # source_detail = leg10_day40.0.hdf5_e8i4j1lev12 (bit-identical to the row above)
    (
        ρ = 0.9960068464279175, T = 283.9228271321616, q_tot = 0.011092031721661148,
        q_lcl = 0.000632087021532389, n_lcl = 9.96530178040129e7,
        q_rai = 0.0004696894067483065, n_rai = 3604.341664401586,
        q_ice = 5.086218276923644e-8, n_ice = 0.055778889412719954,
        q_rim = 4.9061079891157945e-8, b_rim = 5.384917375632014e-11,
        logλ = 7.1727433959224545, w = 0.0, p = 0.0,
    ),
    # source_detail = leg10_day40.0.hdf5_e5i4j4lev10
    (
        ρ = 1.062333345413208, T = 287.5740318619857, q_tot = 0.01232688726968238,
        q_lcl = 0.00012790979921915204, n_lcl = 9.341635789602332e7,
        q_rai = 0.00047672928505538577, n_rai = 1112.3004998710655,
        q_ice = 3.0197526386601386e-8, n_ice = 0.009613760538632226,
        q_rim = 2.998887496838969e-8, b_rim = 3.288923653570723e-11,
        logλ = 6.877435232980331, w = 0.0, p = 0.0,
    ),
    # source_detail = leg15_day60.0.hdf5_e17i1j4lev10
    (
        ρ = 1.0622341632843018, T = 287.5209421756372, q_tot = 0.011991852306550374,
        q_lcl = 0.00025826909115154805, n_lcl = 9.358865251765828e7,
        q_rai = 1.4394195825305385e-6, n_rai = 2.77589621247166,
        q_ice = 0.0, n_ice = 4.680504146330903e-18, q_rim = 0.0, b_rim = 0.0,
        logλ = 12.389472342478946, w = 0.0, p = 0.0,
    ),
    # source_detail = leg15_day60.0.hdf5_e20i1j1lev10 (bit-identical to the row above)
    (
        ρ = 1.0622341632843018, T = 287.5209421756372, q_tot = 0.011991852306550374,
        q_lcl = 0.00025826909115154805, n_lcl = 9.358865251765828e7,
        q_rai = 1.4394195825305385e-6, n_rai = 2.77589621247166,
        q_ice = 0.0, n_ice = 4.680504146330903e-18, q_rim = 0.0, b_rim = 0.0,
        logλ = 12.389472342478946, w = 0.0, p = 0.0,
    ),
    # source_detail = leg15_day60.0.hdf5_e45i4j1lev10 (bit-identical to the row above)
    (
        ρ = 1.0622341632843018, T = 287.5209421756372, q_tot = 0.011991852306550374,
        q_lcl = 0.00025826909115154805, n_lcl = 9.358865251765828e7,
        q_rai = 1.4394195825305385e-6, n_rai = 2.77589621247166,
        q_ice = 0.0, n_ice = 4.680504146330903e-18, q_rim = 0.0, b_rim = 0.0,
        logλ = 12.389472342478946, w = 0.0, p = 0.0,
    ),
    # source_detail = leg15_day60.0.hdf5_e48i4j4lev10 (bit-identical to the row above)
    (
        ρ = 1.0622341632843018, T = 287.5209421756372, q_tot = 0.011991852306550374,
        q_lcl = 0.00025826909115154805, n_lcl = 9.358865251765828e7,
        q_rai = 1.4394195825305385e-6, n_rai = 2.77589621247166,
        q_ice = 0.0, n_ice = 4.680504146330903e-18, q_rim = 0.0, b_rim = 0.0,
        logλ = 12.389472342478946, w = 0.0, p = 0.0,
    ),
    # source_detail = leg15_day60.0.hdf5_e57i2j1lev11
    (
        ρ = 1.0299183130264282, T = 286.4588762801121, q_tot = 0.01236885522139326,
        q_lcl = 0.0010573549244604571, n_lcl = 1.002278478733596e8,
        q_rai = 1.0171887946678992e-6, n_rai = 1571.3658039666507,
        q_ice = 0.0, n_ice = 0.0, q_rim = 0.0, b_rim = 0.0,
        logλ = -Inf, w = 0.0, p = 0.0,
    ),
]
@assert length(CORPUS) == 20 "the corpus must carry all twenty warm-liquid rows"

#####
##### The manual Jacobian's structural zeros
#####
# Species order shared by `MicroState2MP3`, `p3_2m_process_rates` and the manual
# Jacobian: (q_lcl, n_lcl, q_rai, n_rai, q_ice, n_ice, q_rim, b_rim) = indices 1:8.
#
# `_jacobian_2mp3_manual` assembles its return value with `_jacobian_2mp3(FT; kwargs...)`
# (`src/BMT_2mp3_jacobian.jl`), a keyword constructor whose omitted keywords default to
# `zero(FT)`. These 31 `(row, col)` pairs are the keywords that call never passes, so the
# entry is exactly zero at every state, by construction, independent of any numeric
# comparison. Named in `_jacobian_2mp3_manual`'s own species-pair convention
# (`<receiver>_<donor>`) beside each line.
const STRUCTURAL_ZERO_8x8 = [
    (1, 4), (1, 6), (1, 7), (1, 8),         # lcl_nrai, lcl_nice, lcl_rim, lcl_brim
    (2, 4), (2, 6), (2, 7), (2, 8),         # nlcl_nrai, nlcl_nice, nlcl_rim, nlcl_brim
    (3, 2), (3, 4), (3, 6), (3, 7), (3, 8), # rai_nlcl, rai_nrai, rai_nice, rai_rim, rai_brim
    (4, 1), (4, 5), (4, 7), (4, 8),         # nrai_lcl, nrai_ice, nrai_rim, nrai_brim
    (5, 2), (5, 4), (5, 7), (5, 8),         # ice_nlcl, ice_nrai, ice_rim, ice_brim
    (6, 7), (6, 8),                         # nice_rim, nice_brim
    (7, 2), (7, 4), (7, 6), (7, 8),         # rim_nlcl, rim_nrai, rim_nice, rim_brim
    (8, 2), (8, 4), (8, 6), (8, 7),         # brim_nlcl, brim_nrai, brim_nice, brim_rim
]
@assert length(STRUCTURAL_ZERO_8x8) == 31

# `_jacobian_2mp3t_manual`'s temperature column, `col9`, reads only two components of
# `_ice_melting_species`'s output at slots 1 and 2 (`q_lcl`, `n_lcl`), and both are the
# literal zero `_ice_melting_species` always returns there (ice melting never touches
# cloud liquid). `col9[1]` also picks up the condensation saturation-shift term `t1`, so
# it is not structurally zero, but `col9[2]` (the `(n_lcl, T)` entry, row 2 of the 9x9)
# has no other contribution and is exactly zero at every state.
const STRUCTURAL_ZERO_EXTRA_9x9 = [(2, 9)]

# The condensation self-derivative: `docs/src/RosenbrockNumerics.md`'s one directly
# measured entry, "a ratio of 1.0, to four significant figures, at every state" of this
# same twenty-state corpus.
const CONDENSATION_SELF_DERIVATIVE = (1, 1)
const CONDENSATION_SELF_DERIVATIVE_RTOL = 1.0e-4

function mp_and_tps(::Type{FT}) where {FT}
    mp = CMP.Microphysics2MParams(
        FT; with_ice = true, is_limited = true, aerosol = CMP.PrescribedAerosol(FT),
    )
    tps = TDI.TD.Parameters.ThermodynamicsParameters(FT)
    return mp, tps
end

@testset "p3_2m_process_rates slot names and order" begin
    FT = Float64
    mp, tps = mp_and_tps(FT)
    row = CORPUS[6]  # a mixed-phase row, so every slot the docstring names is exercised
    micro = (;
        q_tot = FT(row.q_tot), q_lcl = FT(row.q_lcl), n_lcl = FT(row.n_lcl),
        q_rai = FT(row.q_rai), n_rai = FT(row.n_rai), q_ice = FT(row.q_ice),
        n_ice = FT(row.n_ice), q_rim = FT(row.q_rim), b_rim = FT(row.b_rim),
    )
    thermo = (; ρ = FT(row.ρ), T = FT(row.T), w = FT(row.w), p = FT(row.p), logλ = FT(row.logλ))
    pp, rs = BMT.p3_2m_process_rates(mp, tps, micro, thermo)
    @test keys(pp) == (
        :activation, :cloud_condevap, :rain_evap, :autoconv, :cloud_selfcol,
        :accretion, :rain_selfcol, :rain_breakup, :cloud_numadj, :rain_numadj,
        :cloud_orphan, :rain_orphan, :ice_orphan,
        :liquid_ice_collision, :ice_aggregation, :ice_melting, :ice_deposition,
        :immersion_freezing, :ice_depsub, :ice_numadj, :rain_freezing,
    )
    @test length(pp) == 21
    # the parts-sum-to-total identity holds by construction; assert it directly rather
    # than trusting the construction
    g = BMT.Instantaneous2MP3Tendency(
        mp, tps, FT(row.ρ), FT(row.T), FT(row.q_tot), FT(row.logλ), FT(row.w), FT(row.p),
    )
    x8 = BMT.MicroState2MP3{FT}(
        FT(row.q_lcl), FT(row.n_lcl), FT(row.q_rai), FT(row.n_rai),
        FT(row.q_ice), FT(row.n_ice), FT(row.q_rim), FT(row.b_rim),
    )
    @test sum(values(pp)) == g(x8)
    @test rs.f_shd isa FT
end

for FT in (Float32, Float64)
    mp, tps = mp_and_tps(FT)

    @testset "A1 Jacobian corpus, eight-species state ($FT)" begin
        for (i, row) in enumerate(CORPUS)
            x8 = BMT.MicroState2MP3{FT}(
                FT(row.q_lcl), FT(row.n_lcl), FT(row.q_rai), FT(row.n_rai),
                FT(row.q_ice), FT(row.n_ice), FT(row.q_rim), FT(row.b_rim),
            )
            g8 = BMT.Instantaneous2MP3Tendency(
                mp, tps, FT(row.ρ), FT(row.T), FT(row.q_tot), FT(row.logλ), FT(row.w), FT(row.p),
            )
            f_manual, J_manual = BMT._tendency_and_jacobian(BMT.ManualJacobian(), g8, x8)
            f_exact, J_exact = BMT._tendency_and_jacobian(BMT.ExactJacobian(), g8, x8)

            @testset "state $i" begin
                @test all(isfinite, f_manual)
                @test all(isfinite, f_exact)
                # `ManualJacobian`'s tendency and `ExactJacobian`'s primal value both come
                # from evaluating `p3_2m_process_rates` once and summing the same 21 slots
                # (`ExactJacobian`'s value lane mirrors the primal computation under
                # `ForwardDiff`'s dual arithmetic), so they are expected to agree tightly;
                # this file has not measured how tightly on real compiled code, so the
                # tolerance here is a conservative margin rather than a locked figure.
                @test all(isapprox.(f_manual, f_exact; rtol = FT(1.0e-6), atol = eps(FT)))

                (r, c) = CONDENSATION_SELF_DERIVATIVE
                @test isapprox(
                    J_manual[r, c], J_exact[r, c]; rtol = FT(CONDENSATION_SELF_DERIVATIVE_RTOL),
                )

                for (r, c) in STRUCTURAL_ZERO_8x8
                    @test J_manual[r, c] == zero(FT)
                end
                zeros_set = Set(STRUCTURAL_ZERO_8x8)
                for r in 1:8, c in 1:8
                    (r, c) in zeros_set && continue
                    @test isfinite(J_manual[r, c])
                    @test isfinite(J_exact[r, c])
                end
            end
        end
    end

    @testset "A1 Jacobian corpus, temperature-coupled nine-vector ($FT)" begin
        for (i, row) in enumerate(CORPUS)
            x8 = BMT.MicroState2MP3{FT}(
                FT(row.q_lcl), FT(row.n_lcl), FT(row.q_rai), FT(row.n_rai),
                FT(row.q_ice), FT(row.n_ice), FT(row.q_rim), FT(row.b_rim),
            )
            g8 = BMT.Instantaneous2MP3Tendency(
                mp, tps, FT(row.ρ), FT(row.T), FT(row.q_tot), FT(row.logλ), FT(row.w), FT(row.p),
            )
            _, J_manual8 = BMT._tendency_and_jacobian(BMT.ManualJacobian(), g8, x8)

            y9 = BMT.MicroState2MP3T{FT}(
                FT(row.q_lcl), FT(row.n_lcl), FT(row.q_rai), FT(row.n_rai),
                FT(row.q_ice), FT(row.n_ice), FT(row.q_rim), FT(row.b_rim), FT(row.T),
            )
            g9 = BMT.Temperature2MP3Tendency(
                mp, tps, FT(row.ρ), FT(row.q_tot), FT(row.logλ), FT(row.w), FT(row.p),
            )
            f_manual9, J_manual9 = BMT._tendency_and_jacobian(BMT.TemperatureCoupledJacobian(), g9, y9)
            f_exact9, J_exact9 = BMT._tendency_and_jacobian(BMT.ExactJacobian(), g9, y9)

            @testset "state $i" begin
                @test all(isfinite, f_manual9)
                @test all(isfinite, f_exact9)
                @test all(isapprox.(f_manual9, f_exact9; rtol = FT(1.0e-6), atol = eps(FT)))

                # Ṫ = cᵀf: the temperature-coupled tendency's own ninth slot IS the latent
                # heating of its own species slots, `_temperature_2mp3_tendency`'s literal
                # construction (`docs/src/RosenbrockNumerics.md`: agree to 1e-14 at a
                # representative state; loosened here as this file's own margin).
                Lv = TDI.Lᵥ(tps, FT(row.T))
                Ls = TDI.Lₛ(tps, FT(row.T))
                cp_air = TDI.cpₘ(tps, FT(row.q_tot), FT(row.q_lcl) + FT(row.q_rai), FT(row.q_ice))
                cTf = (Lv * (f_manual9[1] + f_manual9[3]) + Ls * f_manual9[5]) / cp_air
                @test isapprox(f_manual9[9], cTf; rtol = FT(1.0e-10))

                # the species block is `_jacobian_2mp3_manual`'s own output at the same
                # state ("J9's species block matches ManualJacobian's output exactly at
                # Float64, and to within 28 units in the last place at Float32")
                if FT == Float64
                    @test J_manual9[1:8, 1:8] == J_manual8
                else
                    @test all(isapprox.(J_manual9[1:8, 1:8], J_manual8; rtol = FT(1.0e-5)))
                end

                # the temperature row is cᵀf_q and the corner is cᵀf_T, reconstructed
                # independently from the returned species block rather than trusted
                row9_from_block =
                    (Lv .* (J_manual9[1, 1:8] .+ J_manual9[3, 1:8]) .+ Ls .* J_manual9[5, 1:8]) ./
                    cp_air
                @test all(isapprox.(J_manual9[9, 1:8], row9_from_block; rtol = FT(1.0e-8)))
                corner_from_col =
                    (Lv * (J_manual9[1, 9] + J_manual9[3, 9]) + Ls * J_manual9[5, 9]) / cp_air
                @test isapprox(J_manual9[9, 9], corner_from_col; rtol = FT(1.0e-8))

                (r, c) = CONDENSATION_SELF_DERIVATIVE
                @test isapprox(
                    J_manual9[r, c], J_exact9[r, c]; rtol = FT(CONDENSATION_SELF_DERIVATIVE_RTOL),
                )

                zeros9 = Set(vcat(STRUCTURAL_ZERO_8x8, STRUCTURAL_ZERO_EXTRA_9x9))
                for (r, c) in zeros9
                    @test J_manual9[r, c] == zero(FT)
                end
                for r in 1:9, c in 1:9
                    (r, c) in zeros9 && continue
                    @test isfinite(J_manual9[r, c])
                    @test isfinite(J_exact9[r, c])
                end
            end
        end
    end
end
