import Test as TT

TT.@testset "All tests" begin
    include("aerosol_activation_tests.jl")
    include("artifact_calling_tests.jl")
    include("heterogeneous_ice_nucleation_tests.jl")
    include("homogeneous_ice_nucleation_tests.jl")
    include("microphysics0M_tests.jl")
    include("microphysics1M_tests.jl")
    include("bulk_tendencies_tests.jl")
    include("bulk_tendencies_quadrature_tests.jl")
    include("rosenbrock_framework_tests.jl")
    include("rosenbrock_1m_tests.jl")
    include("type_stability_tests.jl")
    include("microphysics2M_tests.jl")
    include("microphysics_noneq_tests.jl")
    include("cloud_diagnostics.jl")
    include("common_functions_tests.jl")
    include("common_types_tests.jl")
    include("nucleation_unit_tests.jl")
    include("precipitation_susceptibility_tests.jl")
    include("p3_tests.jl")
    include("p3_rho_d_stability.jl")
    include("p3_shape_solver_warmstart_tests.jl")
    include("aqua.jl")
    include("performance_tests.jl")
    include("aerosol_activation_calibration.jl")
    include("ice_nucleation_calibration.jl")
    include("ventilation_tests.jl")
    include("ad_compat_tests.jl")
    include("return_type_tests.jl")
    include("DistributionTools_tests.jl")
    include("unrolled_logsumexp.jl")
end
nothing
