agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_04_30

env:
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'

      - echo "--- Instantiate test"
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'
    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --project=test --color=yes test/aerosol_activation_emulators.jl"
 
  - wait: ~
    continue_on_failure: true

  - label: ":envelope: Slack report"
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "cpu_unittests") == "passed" ]; then
        slack-message -c "#microphysics-dev" -x "CloudMicrophysics buildkite-longruns success"
      else
        slack-message -c "#microphysics-dev" -x "CloudMicrophysics buildkite-longruns failure"
      fi