agents:
  queue: central
  slurm_mem: 8G
  modules: climacommon/2025_03_18

env:
  OPENBLAS_NUM_THREADS: 1
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'

      - echo "--- Instantiate test"
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'

      - julia --project=test -e 'using CUDA; CUDA.precompile_runtime()'
      - julia --project=test -e 'using Pkg; Pkg.status()'
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      CLIMACOMMS_DEVICE: "CUDA"
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --project=test --color=yes test/runtests.jl"

  - label: ":flower_playing_cards: GPU unit tests"
    key: "gpu_unittests"
    command:
      - "julia --project=test --color=yes test/gpu_tests.jl"
    env:
      CLIMACOMMS_DEVICE: "CUDA"
    agents:
      slurm_gpus: 1

  - label: ":cyclone: ClimaCore + GPU unit tests"
    key: "clima_core_gpu_unittests"
    command:
      - "julia --project=test --color=yes test/gpu_clima_core_test.jl"
    env:
      CLIMACOMMS_DEVICE: "CUDA"
    agents:
      slurm_gpus: 1
