env:
  JULIA_VERSION: "1.7.0"
  OPENMPI_VERSION: "4.0.4"
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "julia --project -e 'using Pkg; Pkg.add(PackageSpec(name=\"Thermodynamics\", rev=\"orad/refactor-parameters-v1b\"))'"
      - "julia --project -e 'using Pkg; Pkg.add(PackageSpec(name=\"CLIMAParameters\", rev=\"orad/refactor-parameters-v2b\"))'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "init :flower_playing_cards:"
    key: "init_gpu_env"
    command:
      - "julia --project -e 'using Pkg; Pkg.add(PackageSpec(name=\"Thermodynamics\", rev=\"orad/refactor-parameters-v1b\"))'"
      - "julia --project -e 'using Pkg; Pkg.add(PackageSpec(name=\"CLIMAParameters\", rev=\"orad/refactor-parameters-v2b\"))'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"

      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using Pkg; Pkg.add(name=\"CUDA\",version=\"3.5.0\")'"
      - "julia --project -e 'using CUDA; CUDA.versioninfo()'"
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":flower_playing_cards: unit tests"
    key: "gpu_unittests"
    command:
      - "julia --project -e 'using Pkg; Pkg.test(;test_args=[\"CuArray\"])'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
