agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.9.3 cuda/11.8 ucx/1.14.1_cuda-11.8 openmpi/4.1.5_cuda-11.8 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_CPU_TARGET: 'broadwell;skylake'

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'

      - echo "--- Instantiate test"
      - julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'

      - julia --project -e 'using CUDA; CUDA.precompile_runtime()'
      - julia --project -e 'using Pkg; Pkg.status()'
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --project=test --color=yes test/runtests.jl"

  - label: ":flower_playing_cards: unit tests"
    key: "gpu_unittests"
    command:
      - "julia --project=test --color=yes test/gpu_tests.jl"
    agents:
      slurm_gpus: 1
