#=
Generate `docs/src/generated/ParametersReference.md`: which ClimaParams parameters each
CloudMicrophysics parameter struct (and 1-moment process option) reads, and into which fields.

Everything comes from `Parameters.parameter_groups()` / `Parameters.name_map`, i.e. from the same
name maps the constructors are built from (src/parameters/name_maps.jl), so the page cannot drift
from the code; `test/parameter_name_maps_tests.jl` checks that the maps match what the
constructors read. Defaults and descriptions come from the ClimaParams TOML.
Run from `docs/make.jl` before `makedocs`.
=#

import ClimaParams as CP
import CloudMicrophysics.Parameters as CMP

const OUT_DIR = joinpath(@__DIR__, "src", "generated")
const OUT_FILE = joinpath(OUT_DIR, "ParametersReference.md")
const DEFAULTS = CP.create_toml_dict(Float64).data

label(key) = string(CMP.name_map_label(key))
ctor_type(key::Type) = key
ctor_type(key::Tuple) = key[1]
hasdoc(T) = haskey(Base.Docs.meta(CMP), Base.Docs.Binding(CMP, nameof(T)))
link(key) =
    hasdoc(ctor_type(key)) ? "[`$(label(key))`](@ref CloudMicrophysics.Parameters.$(nameof(ctor_type(key))))" :
    "`$(label(key))`"
cell(s) = replace(string(s), "|" => "\\|", "\n" => " ")
function fmt_value(v)
    v isa AbstractVector && length(v) > 4 && return "[" * join(v[1:3], ", ") * ", …] (" * string(length(v)) * " values)"
    v isa AbstractVector && return "[" * join(v, ", ") * "]"
    return string(v)
end
default_of(n) = fmt_value(DEFAULTS[String(n)]["value"])
# ClimaParams descriptions write math as `$...$`; Documenter wants ``...``
description_of(n) = replace(get(DEFAULTS[String(n)], "description", ""), r"\$([^\$]+)\$" => s"``\1``")

mkpath(OUT_DIR)
open(OUT_FILE, "w") do io
    println(
        io,
        """
```@meta
CurrentModule = CloudMicrophysics
```

# Parameter reference

!!! note
    Generated by `docs/generate_parameters_reference.jl` from `Parameters.name_map` and the
    default values of ClimaParams v$(pkgversion(CP)). Do not edit by hand.

For every parameter struct and 1-moment process option: the ClimaParams parameters it reads and
the local names (struct fields, or inputs of derived fields) they map to. Structs built from
other structs (e.g. `Rain` from `ParticleMass(Rain)`) list only what they read themselves.
The last section is the reverse index. See the [Parameters interface](../Parameters.md) page for
how the structs are built and overridden.
""",
    )
    for (title, keys) in CMP.parameter_groups()
        println(io, "## ", title, "\n")
        for key in keys
            nm = CMP.name_map(key)
            println(io, "### ", label(key), "\n")
            println(
                io,
                "Constructor: ",
                link(key),
                key isa Type && key <: CMP.MicrophysicsOption ?
                " (1-moment process option, parameters returned by `process_params_for`)" : "",
                "\n",
            )
            println(io, "| ClimaParams name | Local name | Default | Description |")
            println(io, "|:-----------------|:-----------|:--------|:------------|")
            for (n, f) in pairs(nm)
                println(io, "| `", n, "` | `", f, "` | ", cell(default_of(n)), " | ", cell(description_of(n)), " |")
            end
            println(io)
        end
    end
    index = Dict{Symbol, Vector{String}}()
    for (_, keys) in CMP.parameter_groups(), key in keys, (n, f) in pairs(CMP.name_map(key))
        push!(get!(index, n, String[]), "`" * label(key) * "." * string(f) * "`")
    end
    println(io, "## All ClimaParams parameters used by CloudMicrophysics\n")
    println(
        io,
        length(index),
        " parameters; `Used by` lists `Struct.local_name` for every map that reads the parameter.\n",
    )
    println(io, "| ClimaParams name | Default | Used by | Description |")
    println(io, "|:-----------------|:--------|:--------|:------------|")
    for n in sort!(collect(keys(index)); by = s -> lowercase(string(s)))
        println(
            io,
            "| `",
            n,
            "` | ",
            cell(default_of(n)),
            " | ",
            join(unique(index[n]), ", "),
            " | ",
            cell(description_of(n)),
            " |",
        )
    end
end
@info "Generated $OUT_FILE" maps = sum(length(k) for (_, k) in CMP.parameter_groups())
