[condensation_evaporation_timescale]
value = 39.688722877923894

[rain_autoconversion_timescale]
value = 13353.890619526366

[Variable_time_scale_autoconversion_coeff_alpha]
value = 0.5166975047702738

[rain_terminal_velocity_size_relation_coefficient_chiv]
value = 0.20454276658307452

[rain_terminal_velocity_size_relation_coefficient_delv]
value = 0.22763691994393714

[rain_cross_section_size_relation_coefficient_chia]
value = 16.60537462650898

[rain_cross_section_size_relation_coefficient_dela]
value = 2.997519288341676

[rain_ventilation_coefficient_b]
value = 0.9779279811508783
